services:
  postgres:
    image: 'postgres:latest'
    container_name: shortify_postgres
    shm_size: 128mb
    environment:
      - 'POSTGRES_DB=shortify'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    restart: unless-stopped

volumes:
  postgres:
